#!/usr/bin/python

# Alex Lee (https://github.com/alexlee002/osx_helper)
# License: Apache License: https://github.com/alexlee002/osx_helper/blob/master/LICENSE

from __future__ import print_function
import os.path
import sys


#######################################################
# Utils
#######################################################
if sys.version_info[:2] < (3, 3):
    old_print = print
    def print(*args, **kwargs):
        flush = kwargs.pop('flush', False)
        old_print(*args, **kwargs)
        if flush:
            file = kwargs.get('file', sys.stdout)
            file.flush() if file is not None else sys.stdout.flush()

def to_unicode(val):
    """ safely convert an object to unicode """
    return val if isinstance(val, unicode) else str(val).decode('utf-8')


def green_msg(msg):
    return ('\033[32m{0}\033[0m'.format(msg))


def yellow_msg(msg):
    return ('\033[33m{0}\033[0m'.format(msg))


def red_msg(msg):
    return ('\033[1;31m{0}\033[0m'.format(msg))


def copy(src, dest, force=True):
    import shutil, errno, datetime

    assert src != dest

    if os.path.isdir(dest):
        if force:
            shutil.rmtree(dest)
        else:
            subfix = u'-{t}'.format(t=datetime.datetime.now().strftime('%Y%m%d_%H%M%S'))
            os.rename(dest, dest+subfix)
    elif os.path.exists(dest):
        if force:
            os.remove(dest)
        else:
            subfix = u'-{t}'.format(t=datetime.datetime.now().strftime('%Y%m%d_%H%M%S'))
            name, ext = os.path.splitext(dest)
            os.rename(dest, u'{n}{s}{e}'.format(n=name, s=subfix, e=ext))

    mkdirs(os.path.dirname(dest))

    if os.path.isdir(src):
        # shutil.copytree(src, dest, symlinks=True, \
        #     ignore=lambda p,items:[x for x in items if os.path.islink(os.path.join(p, x))])
        shutil.copytree(src, dest, symlinks=True)
    elif os.path.isfile(src):
        shutil.copy(src, dest)


def mkdirs(path):
    import errno
    try:
        os.makedirs(path)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise

def exec_shell(cmd):
    import subprocess, sys
    return subprocess.call(cmd, shell=True)

#####################################################################

def load_config(file):
    import json

    configs = None
    with open(file, u'rb') as fp:
        json_str = ''
        for line in fp:
            if not to_unicode(line).strip().startswith(u'//'):
                json_str += line
        try:
            return json.loads(json_str)
        except ValueError as e:
            print(red_msg(u'Invalid config file!'));
            raise


def process_file_path(path, restore=False):
    if restore:
        if path.startswith(u'$HOME'):
            path = path.replace(u'$HOME', '~', 1)
        elif path.startswith(u'$ROOT'):
            path = path.replace(u'$ROOT/', '/', 1)
    else:
        if path.startswith(u'~'):
            path = path.replace(u'~', u'$HOME', 1)
        else:
            path = os.path.abspath(path)
            if path.startswith(u'/'):
                path = path.replace(u'/', u'$ROOT/', 1)
    return path

####################################################################
def backup_files(files, dest_dir):
    """
    backup specified files to dest_dir.

    Args:
        files:      list of file paths
        dest_dir:   the root path to store backup-files
    """
    for p in files:
        srcpath = os.path.abspath(os.path.expanduser(p))
        destpath = os.path.join(dest_dir, process_file_path(p))

        if os.path.exists(srcpath):
            print(u'backing up {0} ... '.format(p), end=u'', flush=True)
            try:
                copy(srcpath, destpath)
                print(green_msg(u'OK'))
            except OSError as e:
                print(red_msg(u'Failed'))
                raise


def restore_files(files, bakup_dir):
    """
    restore files from backup_dir.

    Args:
        files:      list, the files to restore
        backup_dir: str, the root backup dir
    """
    for p in files:
        bakup_f = os.path.join(bakup_dir, process_file_path(p))
        if os.path.exists(bakup_f):
            print(u'restoring {0} from {1} ... '.format(p, bakup_f), end=u'', flush=True)
            try:
                restore_path = os.path.abspath(os.path.expanduser(p))
                if os.path.isdir(restore_path):
                    # restore destpath is exist and isdir
                    for sf in os.listdir(bakup_f):
                        copy(os.path.join(bakup_f, sf), os.path.join(restore_path, sf))
                else:
                    copy(bakup_f, restore_path, force=False)
                print(green_msg(u'OK'))
            except OSError as e:
                print(red_msg(u'Failed'))
                raise

#########################################################################
def backup_defaults(domains, dest_dir):
    if len(domains) > 0:
        mkdirs(dest_dir)

    for name in domains:
        plist_file = os.path.join(dest_dir, u'{0}.plist'.format(name))
        if exec_shell(u'defaults export {0} {1}'.format(name, plist_file)) == 0:
            print(u'export {0} {1}'.format(name, green_msg(u'OK')))
        else:
            print(u'export {0} {1}'.format(name, red_msg(u'Failed')))


def restore_defaults(domains, bakup_dir):
    # backup the existed plist before restore from backup
    safe_bakup_dir = os.path.expanduser(u'~/Desktop/orig-defaults-pre_restore')
    mkdirs(safe_bakup_dir)
    for name in domains:
        orig_plist = os.path.join(safe_bakup_dir, u'{0}.plist'.format(name))
        exec_shell(u'defaults export {0} {1}'.format(name, orig_plist))

        bak_plist = os.path.join(bakup_dir, u'{0}.plist'.format(name))
        if exec_shell(u'defaults import {0} {1}'.format(name, bak_plist)) == 0:
            print(u'import {0} {1}'.format(name, green_msg(u'OK')))
        else:
            print(u'import {0} {1}'.format(name, red_msg(u'Failed')))


#########################################################################
def install_brews(brews):
    """ install apps via homebrew or cask """
    for cfg in brews:
        if u'tap' in cfg:
            if exec_shell(u'brew tap {0}'.format(cfg[u'tap'])) != 0:
                continue
        if u'cask_ids' in cfg:
            cask_list = cfg[u'cask_ids']
            exec_shell(u'brew cask install {0}'.format(u' '.join(cask_list)))
        if u'brew_ids' in cfg:
            brew_list = cfg[u'brew_ids']
            exec_shell(u'brew install {0}'.format(u' '.join(brew_list)))


def sys_optimize(configs):
    cmd = u'; '.join(configs)
    exec_shell(cmd)


def install_homebrew():
    if exec_shell(u'brew --version') != 0:
        print(u'=== Installing homebrew ...')
        cmd = u'/usr/bin/ruby -e\
         "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
        if exec_shell(cmd) == 0:
            print(green_msg(u'Install homebrew OK'))
        else:
            print(red_msg(u'Install homebrew Failed'))
            return False
    return True


def config_zsh(init=False):
    """
    configure zsh:
        install oh-my-zsh
    oh-my-zsh theme: powerlevel9k
    oh-my-zsh plugins: 

    Args:
        init:   True if newly install, False if restore from backup files
    """

    has_zshrc = os.path.isfile(os.path.expanduser(u'~/.zshrc'))

    cmd = u'sh -c "$(curl -fsSL '
    cmd += u'https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh '
    cmd += u'| sed -e $\'s/env zsh -l/#env zsh -l/\')"'
    print(u'=== Configuring zsh ...')
    if exec_shell(cmd) != 0:
        print(red_msg(u'install oh-my-zsh Failed'))
        return
    print(green_msg(u'install oh-my-zsh OK'))

    # clone powerlevel9k theme
    cmd = u'git clone https://github.com/bhilburn/powerlevel9k.git '
    cmd += u'~/.oh-my-zsh/custom/themes/powerlevel9k; '
    # clone plugin: zsh-syntax-highlighting
    cmd += u'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git '
    cmd += u'~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting;'
    # clone plugin: zsh-autosuggestions
    cmd += u'git clone git://github.com/zsh-users/zsh-autosuggestions '
    cmd += u'~/.oh-my-zsh/custom/plugins/zsh-autosuggestions;'

    if not has_zshrc:
        cmd = u'cat ~/.zshrc'
        quote_newline = u'\\\\\\n'

        search = u'^export ZSH='
        settings = (
            u'export ZSH=$HOME/.oh-my-zsh',
            u'source $HOME/.bash_profile' \
                if os.path.isfile(os.path.expanduser(u'~/.bash_profile')) else u'',
            u'export TERM="xterm-256color"',
        )
        replacement = quote_newline.join([l.replace(u'/', u'\\\/') for l in settings])
        replacement += quote_newline +u'#export ZSH='
        cmd += u' | sed -e $\'s/{s}/{r}/\''.format(s=search, r=replacement)

        search = u'^ZSH_THEME='
        settings = (
            u'POWERLEVEL9K_MODE="nerdfont-complete"',
            u'ZSH_THEME=powerlevel9k/powerlevel9k',
            u'POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)',
            u'POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)',
            u'DEFAULT_USER="{u}"'.format(u=os.getlogin()),
            #POWERLEVEL9K_DIR_PATH_SEPARATOR="%F "$'\uE0B1'" %F"
            u'POWERLEVEL9K_DIR_PATH_SEPARATOR="%F "$\\\'\\\\\\\\uE0B1\\\'" %F"'
        )
        replacement = quote_newline.join([l.replace(u'/', u'\\\/') for l in settings]) 
        replacement += quote_newline + u'#ZSH_THEME='
        cmd += u' | sed -e $\'s/{s}/{r}/\''.format(s=search, r=replacement)

        search = u'^plugins=('
        ext_plugins = (
            u'  zsh-syntax-highlighting',
            u'  zsh-autosuggestions',
            u'  OSX',
            u'  Z',
            u'  sublime'
        )
        replacement = u'plugins=({nl}{pl}'.format(nl=quote_newline, pl=quote_newline.join(ext_plugins))
        import datetime
        cur_time = datetime.datetime.today().strftime('%Y%m%d-%H%M%S')
        tmpfile = u'~/.zshrc-{t}'.format(t=cur_time)
        cmd += u' | sed -e $\'s/{s}/{r}/\' > {f}'.format(s=search, r=replacement, f=tmpfile)
        cmd += u' && mv -f $HOME/.zshrc ~/.zshrc-orig-{t}'.format(t=cur_time)
        cmd += u' && mv -f {tmpfile} ~/.zshrc'.format(tmpfile=tmpfile)
        cmd += u' && env zsh -l && source ~/.zshrc'
    else:
        cmd += u'env zsh -l && source ~/.zshrc'
    if exec_shell(cmd) != 0:
        print(red_msg(u'config zsh Failed'))
    else:
        print(green_msg(u'config zsh OK'))


#########################################################################
def backup(dest_dir):
    cfgfile = os.path.abspath(os.path.join(os.path.dirname(__file__), u'osx_helper.json'))
    configs = load_config(cfgfile)

    if u'files' in configs:
        backup_files(configs[u'files'], os.path.join(dest_dir, u'files'))

    if u'defaults' in configs:
        backup_defaults(configs[u'defaults'], os.path.join(dest_dir, u'plists'))


def restore(bakup_dir):
    brew_installed = install_homebrew()

    cfgfile = os.path.abspath(os.path.join(os.path.dirname(__file__), u'osx_helper.json'))
    configs = load_config(cfgfile)

    if u'osx_config' in configs:
        sys_optimize(configs[u'osx_config'])

    if u'files' in configs:
        restore_files(configs[u'files'], os.path.join(bakup_dir, u'files'))

    if u'defaults' in configs:
        restore_defaults(configs[u'defaults'], os.path.join(bakup_dir, u'plists'))

    if u'brews' in configs and brew_installed:
        install_brews(configs[u'brews'])

    config_zsh()


def init_os():
    brew_installed = install_homebrew()

    cfgfile = os.path.abspath(os.path.join(os.path.dirname(__file__), u'osx_helper.json'))
    configs = load_config(cfgfile)

    if u'osx_config' in configs:
        sys_optimize(configs[u'osx_config'])
    
    if u'brews' in configs and brew_installed:
        install_brews(configs[u'brews'])

    config_zsh(init=True)

###################################################
def usage():

    usage = """
    backup path     backup profiles, files, apps and defaults to path
    restore path    restore profiles, files, apps and defaults from path
    init            init a new os

    the action of backup/restore is configured via osx_helper.json
    """
    
    print(u'{0} backup/restore path'.format(sys.argv[0]))
    print(usage)


def main():
    def __checkArgs(cnt):
        if len(sys.argv) < cnt:
            usage()
            sys.exit(-1)

    __checkArgs(2)
    action = sys.argv[1]
    if action == u'backup':
        __checkArgs(3)
        path = os.path.expanduser(sys.argv[2])
        mkdirs(path)
        backup(path)
        print(green_msg(u'=== backup DONE! ==='))
    elif action == u'restore':
        __checkArgs(3)
        path = os.path.expanduser(sys.argv[2])
        if os.path.isdir(path):
            restore(path)
            print(green_msg(u'=== restore DONE! ==='))
        else:
            print(red_msg(u'{0} not a backup dir.'.format(path)))
            sys.exit(-1)
    elif action == u'init':
        init_os()
        print(green_msg(u'=== init DONE! ==='))
    else:
        usage()
        sys.exit(-1)


if __name__ == '__main__':
    main()

